import Head from 'next/head';
import React from 'react';
import SecondLayout from '../../components/Layout/SecondLayout';
import LoginLayout from '../../components/NestedLayouts/LoginLayouts/LoginLayout';
import LoginFeature from '../../features/Login';

const Login = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> Login | Foody Delivery</title>
      </Head>
      <LoginFeature />
    </>
  );
};

Login.getLayout = () => {
  return (
    <SecondLayout>
      <LoginLayout>{<Login />}</LoginLayout>
    </SecondLayout>
  );
};

export default Login;
