import Head from "next/head";
import FaqContainer from "../../features/FAQ/FaqContainer";

const Faq = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> FAQ | Foody Delivery</title>
      </Head>
      <FaqContainer />
    </>
  );
};

export default Faq;
