import React from "react";
import Head from "next/head";
import AboutContent from "../../features/About/AboutContainer";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const AboutUs = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> About | Foody Delivery</title>
      </Head>
      <AboutContent />
    </>
  );
};

export async function getStaticProps({ locale }) {
  let languages = {
    ...(await serverSideTranslations(locale, ["common", "menu"])),
  };

  return {
    props: {
      ...languages,
    },
  };
}

export default AboutUs;
