import HowItWorksContainer from "../../features/HowItWorks/HowItWorksContainer";
import Head from "next/head";

const HowItWork = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title> How It Works | Foody Delivery</title>
      </Head>
      <HowItWorksContainer />
    </>
  );
};

export default HowItWork;
